#!/bin/sh
# @author Evgeni Genchev
# @date 2022-12-19 11:09


COLOR_GOOD="#8EC07C"
COLOR_OK="#FABD2F"
COLOR_BAD="#9D0025"
COLOR_PKG="#b380c2"

##################################### BLOCKS ###############################################
layout(){
	LG=$(xset -q | grep LED | awk '{print $10}')
	
	case "$LG" in 
		"00000000" ) dat="{ \"full_text\": \"us\", \"color\":\"#8EC07C\" }" ;;
		"00000001" ) dat="{ \"full_text\": \"US\", \"color\":\"#98971a\" }" ;;
		"00001000" ) dat="{ \"full_text\": \"бг\", \"color\":\"#076678\" }" ;;
		"00001001" ) dat="{ \"full_text\": \"БГ\", \"color\":\"#458588\" }" ;;
		*) dat="{ \"full_text\": \"??\", \"color\":\"#928374\" }" ;;
	esac

	echo -n $dat
}

private_ip(){

	INTERNET_MODULE="wlan0"
	PRIVATE_IP=$(ip a | grep "192.168" | awk '/inet/ {print $2}' | cut -f1 -d"/")
	SIGNAL_STRENGTH=$(cat /proc/net/wireless | grep 'wlan0' | tr -s " " | cut -d " " -f 4 | cut -f1 -d".")
	
	echo -n ',{'
	echo -n "\"name\":\"id_local_ip\","
	echo -n "\"full_text\":\"$PRIVATE_IP\","
	
	if [ -n $SIGNAL_STRENGTH ]; then
		if [ $SIGNAL_STRENGTH -gt 39 ]; then
			echo -n "\"color\": \"$COLOR_GOOD\""
		elif [ $SIGNAL_STRENGTH -gt 19 ]; then		
			echo -n "\"color\": \"$COLOR_OK\""
		else
			echo -n "\"color\": \"$COLOR_BAD\""
		fi
	else
		echo -n "\"color\": \"$COLOR_GOOD\""
	fi
	
	echo -n "}"

}

battery(){

	BAT="BAT1" #check your own battery

	if [ -f /sys/class/power_supply/$BAT/uevent ]; then
		CAPACITY=$(cat /sys/class/power_supply/$BAT/uevent | grep "CAPACITY=" | cut -d'=' -f2)
		
		SUPPLY_STATUS=$(cat /sys/class/power_supply/$BAT/uevent | grep "STATUS=" | cut -d'=' -f2)
		echo -n ',{'
		echo -n "\"name\":\"id_battery\","
		
		if [ $SUPPLY_STATUS == "Charging" ]; then
			echo -n "\"full_text\":\" $CAPACITY%\","
			echo -n "\"color\": \"$COLOR_OK\""
		
		elif [ $CAPACITY -eq 100 ]; then
			echo -n "\"full_text\":\" $CAPACITY%\","
			echo -n "\"color\": \"$COLOR_BAD\""
		
		elif [ $CAPACITY -lt 21 ]; then
			echo -n "\"full_text\":\" $CAPACITY%\","
			echo -n "\"color\": \"$COLOR_BAD\""
		
		else
			echo -n "\"full_text\":\" $CAPACITY%\""
		fi

		echo -n "}"
	fi
}

disk_usage(){
	DISK_INFO=$(df -h /home | tail -n1 | tr -s " ")
	TOTAL=$(echo $DISK_INFO | cut -d " " -f 2)
	USED=$(echo $DISK_INFO | cut -d " " -f 3)
	FREE=$(echo $DISK_INFO | cut -d " " -f 4)
	PRCT_USED=$(echo $DISK_INFO | cut -d " " -f 5)

	echo -n ',{'
	echo -n "\"name\":\"id_disk\","
	echo -n "\"full_text\":\" $USED/$TOTAL\""
	echo -n "}"
}

volume_pamixer() {
	VOL=$(pamixer --get-volume)
	IS_MUTE=$(pamixer --get-mute)
	echo -n ',{'
	echo -n "\"name\":\"id_vol\","

	if [[ $IS_MUTE == "true" ]]; then

		echo -n "\"color\": \"$COLOR_OK\","
		echo -n "\"full_text\":\"♪ muted ($VOL%)\","
	else
		echo -n "\"full_text\":\"♪ $VOL%\","
	fi
		echo -n "\"instance\":\"default.Master.0\","
		echo -n "\"markup\":\"none\""
	echo -n "}"
}

dtime() {
	DATE=$(date "+%Y-%m-%d %H:%M")
	echo -n ',{'
	echo -n "\"name\":\"id_dtime\","
	echo -n "\"full_text\":\" $DATE \""
	echo -n "}"
}

pkg() {
	N_PKG=$(pacman -Qq | wc -l)
	echo -n ',{'
	echo -n "\"name\":\"id_pkg\","
	echo -n "\"color\": \"$COLOR_PKG\","
	echo -n "\"full_text\":\"  $N_PKG \""
	echo -n "}"
}

################################# END BLOCKS ###############################################


################################## ACTIONS #################################################
calendar_action(){
	TODAY=$(date '+%-d')
	HEAD=$(cal | head -n1)
	BODY=$(cal | tail -n7 | sed -z "s|$TODAY|<u><b>$TODAY</b></u>|1")
	FOOT="\n\t<i>~calendar</i> "

	dunstify "$HEAD" "$BODY$FOOT"
}

volume_pamixer_action(){
	IS_MUTE=$(pamixer --get-mute)
	if [[ $IS_MUTE == "true" ]]; then
		pamixer --unmute
	else
		pamixer --mute 
	fi

}

disk_action(){
	
	DISK_INFO=$(df -h /home | tail -n1 | tr -s " ")
	TOTAL=$(echo $DISK_INFO | cut -d " " -f 2)
	USED=$(echo $DISK_INFO | cut -d " " -f 3)
	FREE=$(echo $DISK_INFO | cut -d " " -f 4)
	PRCT_USED=$(echo $DISK_INFO | cut -d " " -f 5)

	MSG="TOTAL:\t$TOTAL\nUSED:\t$USED\nUSED%:\t$PRCT_USED\nFREE:\t$FREE"

	dunstify " Disk Info" "$MSG"
}
################################# END ACTIONS ##############################################

echo '{"version":1, "click_events": true}'
echo '['
echo '[]'

(while :;
do
	echo -n ",["
	layout
	pkg
	volume_pamixer
	private_ip
	battery
	disk_usage
	dtime
	echo -n "]"
	echo
		sleep 0.5
done) &

while read line;
do
	if [[ $line == *"name"*"id_dtime"* ]]; then
		calendar_action &

	elif [[ $line == *"name"*"id_vol"* ]]; then
		volume_pamixer_action &
	
	elif [[ $line == *"name"*"id_disk"* ]]; then
		disk_action &
	
	fi

done
